# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"singleton": "01_data.sql.ipynb",
         "DB": "01_data.sql.ipynb",
         "get_db_engine": "01_data.sql.ipynb",
         "get_db_session": "01_data.sql.ipynb",
         "ts_from_df_row": "02_data.importer.buoy_data.ipynb",
         "import_buoy_realtime_wave_detail": "02_data.importer.buoy_data.ipynb",
         "import_buoy_raw_spectral_wave_data": "02_data.importer.buoy_data.ipynb",
         "default_args": "03_dag.buoy_data.ipynb",
         "dag": "03_dag.buoy_data.ipynb",
         "get_all_active_buoy_station_ids": "03_dag.buoy_data.ipynb",
         "run_import_buoy_realtime_wave_detail": "03_dag.buoy_data.ipynb",
         "import_buoy_realtime_wave_detail_tasks": "03_dag.buoy_data.ipynb",
         "active_station_ids": "03_dag.buoy_data.ipynb",
         "run_import_buoy_raw_spectral_wave_data": "03_dag.buoy_data.ipynb",
         "t2": "03_dag.buoy_data.ipynb",
         "slack_token": "03_dag.buoy_data.ipynb",
         "slack_success_task": "03_dag.buoy_data.ipynb",
         "Buoy": "04_data.models.buoy.ipynb",
         "BuoyRawSpectralWaveData": "05_data.models.log_entry.ipynb",
         "LogEntry": "05_data.models.log_entry.ipynb"}

modules = ["data/sql.py",
           "data/importer/buoy_data.py",
           "dag/buoy_data.py",
           "data/models/buoy.py",
           "data/models/log_entry.py",
           "data/exporter.py"]

doc_url = "https://yipstar.github.io/huey/"

git_url = "https://github.com/yipstar/huey/tree/master/"

def custom_doc_links(name): return None
