# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/02_data.importer.buoy_data.ipynb (unless otherwise specified).

__all__ = ['ts_from_df_row', 'import_buoy_realtime_wave_detail', 'import_buoy_raw_spectral_wave_data']

# Cell
from ...imports import *

# Cell
from ..sql import get_db_engine

# Cell
def ts_from_df_row(row):
        return datetime(
            int(row['#YY']),
            int(row['MM']),
            int(row['DD']),
            int(row['hh']),
            int(row['mm']),
            tzinfo=timezone.utc)

# Cell
def import_buoy_realtime_wave_detail(station_id):
    db_engine = get_db_engine()
    sql = f"select * from buoy where station_id='{station_id}'"
    buoy = pd.read_sql(sql, db_engine).iloc[0]

    sql = f"select * from buoy_realtime_wave_detail order by ts desc limit 1"
    latest_ob = pd.read_sql(sql, db_engine, parse_dates=['ts']).iloc[0]

    station_id = "46025"
    realtime_url = f"https://www.ndbc.noaa.gov/data/realtime2/{station_id}.spec"
    df = pd.read_csv(realtime_url, delim_whitespace=True)

    df["buoy_id"] = buoy.id

    df = df.replace('MM', np.NaN)

    df2 = df.rename(columns={
        "WVHT": "significant_wave_height",
        "SwH": "swell_height",
        "SwP": "swell_period",
        "SwD": "swell_direction",
        "WWH": "wind_wave_height",
        "WWP": "wind_wave_period",
        "WWD": "wind_wave_direction",
        "STEEPNESS": "steepness",
        "APD": "average_wave_period",
        "MWD": "dominant_wave_direction"
    })

    # skip first row
    df2 = df2[1:]

    def ts_from_df_row(row):
        return datetime(
            int(row['#YY']),
            int(row['MM']),
            int(row['DD']),
            int(row['hh']),
            int(row['mm']),
            tzinfo=timezone.utc)

    df2["ts"] = df2.apply(lambda row: ts_from_df_row(row), axis=1)
    df2 = df2.drop(columns=['#YY', 'MM', 'DD', 'hh', 'mm'])
    #df2 = df2.drop(columns=['MWD'])

    sql = f"select * from buoy_realtime_wave_detail order by ts desc limit 1"
    latest_ob = pd.read_sql(sql, db_engine, parse_dates=['ts']).iloc[0]

    # only insert latest obs not in the db already
    df2_latest = df2[df2.ts > latest_ob.ts]

    df2_latest.to_sql('buoy_realtime_wave_detail', con=db_engine, if_exists='append', index=False)

    return df2_latest

# Cell
from ..sql import get_db_session
from ..models.buoy import Buoy, BuoyRawSpectralWaveData

# Cell
def import_buoy_raw_spectral_wave_data(station_id):
    db_session = get_db_session()

    buoy = db_session.query(Buoy).filter(Buoy.station_id == station_id).first()
    latest_ob = db_session.query(BuoyRawSpectralWaveData).filter(BuoyRawSpectralWaveData.buoy_id == buoy.id ).order_by(BuoyRawSpectralWaveData.ts.desc()).first()

    raw_spec_url = f"https://www.ndbc.noaa.gov/data/realtime2/{station_id}.data_spec"
    response = requests.get(raw_spec_url)
    data = response.text

    for line in data.splitlines()[1:]:

        ob = BuoyRawSpectralWaveData.from_data_line(line)
        ob.buoy = buoy

        if (latest_ob is None or ob.ts > latest_ob.ts):
            print(f"inserting observation for date: {ob.ts}")
            db_session.add(ob)
        else:
            print(f"observation for date: {ob.ts} already present, skipping.")
            break

    db_session.commit()
    print("import complete")

    return data